from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np


def parse_args() -> argparse.Namespace:
    """Parse CLI arguments for baseline metric aggregation."""
    parser = argparse.ArgumentParser(
        description="Aggregate one or more 2D baseline JSON reports into a fold summary."
    )
    parser.add_argument(
        "reports",
        nargs="+",
        type=Path,
        help="Paths to JSON reports generated by train_baseline_2d.py.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("artifacts") / "baseline_metrics_2d_aggregate.json",
        help="Where to write the aggregated summary.",
    )
    return parser.parse_args()


def summarize(values: list[float]) -> dict[str, float]:
    """Return mean, std, min, and max for a numeric list."""
    array = np.asarray(values, dtype=float)
    return {
        "mean": round(float(array.mean()), 6),
        "std": round(float(array.std(ddof=0)), 6),
        "min": round(float(array.min()), 6),
        "max": round(float(array.max()), 6),
    }


def main() -> None:
    """Aggregate fold metrics into a single benchmarking summary."""
    args = parse_args()
    reports: list[dict] = []
    for report_path in args.reports:
        reports.append(json.loads(report_path.read_text()))

    best_val_dice = [float(report["best_val_dice"]) for report in reports if report["best_val_dice"] is not None]
    best_val_loss = [float(report["best_val_loss"]) for report in reports if report["best_val_loss"] is not None]

    per_class: dict[str, list[float]] = {}
    for report in reports:
        class_names = report.get("class_names", [])
        class_scores = report.get("best_val_dice_per_class")
        if class_scores is None:
            continue
        for class_name, score in zip(class_names, class_scores, strict=False):
            per_class.setdefault(str(class_name), []).append(float(score))

    summary = {
        "num_reports": len(reports),
        "report_paths": [str(path) for path in args.reports],
        "best_val_dice": summarize(best_val_dice),
        "best_val_loss": summarize(best_val_loss),
        "best_val_dice_per_class": {
            class_name: summarize(scores) for class_name, scores in sorted(per_class.items())
        },
        "folds": [
            {
                "fold": report["config"]["fold"],
                "best_epoch": report["best_epoch"],
                "best_val_dice": report["best_val_dice"],
                "best_val_loss": report["best_val_loss"],
                "best_val_dice_per_class": report["best_val_dice_per_class"],
                "checkpoint_path": report["checkpoint_path"],
            }
            for report in reports
        ],
    }

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(summary, indent=2))

    print(f"Reports: {len(reports)}")
    print(f"Best val Dice mean/std: {summary['best_val_dice']['mean']:.4f} / {summary['best_val_dice']['std']:.4f}")
    print(f"Saved aggregate summary to: {args.output}")


if __name__ == "__main__":
    main()
